### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by Shazgul** [Hadesy2k/sqlivulscan#2]
Used Mode:
2

Used Dork:
league.php?id=

Full Log:  Website Information

 Domain Name : github.com
 Protocol    : https
 Path        : /paquettg/leaguewrap/blob/master/src/LeagueWrap/Api/League.php
 Query[s]    : 

Checking the Website whether it's up or down.
[+] Connected, URL is valid.

Traceback (most recent call last):
  File "sqlivul.py", line 246, in <module>
    main()
  File "sqlivul.py", line 89, in __init__
    self.urlreq(self.readfile())
  File "sqlivul.py", line 124, in urlreq
    self.scanurl(site)
  File "sqlivul.py", line 206, in scanurl
    parms = dict([item.split("=") for item in parsed_url[4].split("&")])
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by Hadesy2k** [comment]
Okay I fixed the code in **line 203** of `sqlivul.py` to handle no query cases. It should be able to handle it by now. Thanks for your comment.
